export * from './academic-year.repository'
export * from './event.repository'
export * from './event-preset.repository'
export * from './lecturer.repository'
export * from './schedule.repository'
export * from './subject.repository'
export * from './user.repository'
